// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./internal/models/models.js";

/**
 * Close closes the database connection
 */
export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2566110416);
}

/**
 * GetDailyStats returns statistics for a specific date
 */
export function GetDailyStats(date: string): $CancellablePromise<models$0.DailyData | null> {
    return $Call.ByID(578614904, date).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetOverview returns the overall screen time overview
 */
export function GetOverview(): $CancellablePromise<models$0.ScreenTimeOverview | null> {
    return $Call.ByID(3560258107).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTodayStats returns today's statistics
 */
export function GetTodayStats(): $CancellablePromise<models$0.DailyData | null> {
    return $Call.ByID(1427620456).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.DailyData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.ScreenTimeOverview.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
