// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppData represents application usage data for the frontend
 */
export class AppData {
    "class": string;
    "total_time": number;
    "total_time_formatted": string;
    "open_count": number;
    "last_seen": string;
    "percentage": number;

    /** Creates a new AppData instance. */
    constructor($$source: Partial<AppData> = {}) {
        if (!("class" in $$source)) {
            this["class"] = "";
        }
        if (!("total_time" in $$source)) {
            this["total_time"] = 0;
        }
        if (!("total_time_formatted" in $$source)) {
            this["total_time_formatted"] = "";
        }
        if (!("open_count" in $$source)) {
            this["open_count"] = 0;
        }
        if (!("last_seen" in $$source)) {
            this["last_seen"] = "";
        }
        if (!("percentage" in $$source)) {
            this["percentage"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppData instance from a string or object.
     */
    static createFrom($$source: any = {}): AppData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppData($$parsedSource as Partial<AppData>);
    }
}

/**
 * DailyData represents daily usage data
 */
export class DailyData {
    "date": string;
    "total_time": number;
    "total_time_formatted": string;
    "apps": AppData[];

    /** Creates a new DailyData instance. */
    constructor($$source: Partial<DailyData> = {}) {
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("total_time" in $$source)) {
            this["total_time"] = 0;
        }
        if (!("total_time_formatted" in $$source)) {
            this["total_time_formatted"] = "";
        }
        if (!("apps" in $$source)) {
            this["apps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DailyData instance from a string or object.
     */
    static createFrom($$source: any = {}): DailyData {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("apps" in $$parsedSource) {
            $$parsedSource["apps"] = $$createField3_0($$parsedSource["apps"]);
        }
        return new DailyData($$parsedSource as Partial<DailyData>);
    }
}

/**
 * ScreenTimeOverview represents the overall screen time data
 */
export class ScreenTimeOverview {
    "total_time": number;
    "total_time_formatted": string;
    "today_time": number;
    "today_time_formatted": string;
    "top_apps": AppData[];

    /** Creates a new ScreenTimeOverview instance. */
    constructor($$source: Partial<ScreenTimeOverview> = {}) {
        if (!("total_time" in $$source)) {
            this["total_time"] = 0;
        }
        if (!("total_time_formatted" in $$source)) {
            this["total_time_formatted"] = "";
        }
        if (!("today_time" in $$source)) {
            this["today_time"] = 0;
        }
        if (!("today_time_formatted" in $$source)) {
            this["today_time_formatted"] = "";
        }
        if (!("top_apps" in $$source)) {
            this["top_apps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenTimeOverview instance from a string or object.
     */
    static createFrom($$source: any = {}): ScreenTimeOverview {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("top_apps" in $$parsedSource) {
            $$parsedSource["top_apps"] = $$createField4_0($$parsedSource["top_apps"]);
        }
        return new ScreenTimeOverview($$parsedSource as Partial<ScreenTimeOverview>);
    }
}

// Private type creation functions
const $$createType0 = AppData.createFrom;
const $$createType1 = $Create.Array($$createType0);
